### ISSUE TITLE
config cookie gets cached

### ISSUE THREAD

**Issue by mhamann** [HenrikJoreteg/clientconfig#5]
When I set the `config` cookie on the server (using Express), it seems to get cached on the browser. Then, if another app on the same domain sets another `config` cookie, it doesn't seem to get set properly and instead I see the "old" cookie.

Are there any recommendations for ensuring that the proper cookie data gets collected by the browser? I suppose this only affects situations where one might be using multiple native web apps as part of the same solution.

**Comment by mhamann** [comment]
@HenrikJoreteg any comments?

**Comment by HenrikJoreteg** [comment]
Seems like this would be an issue with how express is configured. Probably caching that somehow. I've added you as a collaborator on this, so if you figure it out, feel free to leave a note in the readme. Might be worth adding a caveat to the readme either way.

**Comment by HenrikJoreteg** [comment]
also, would be happy for help maintaining this module, if you're game.

**Comment by mhamann** [comment]
Yep, I will work on this project along with `cookie-getter`, since they go hand-in-hand.

Don't think I've seen this issue recently, so may have been my own mistake. Will close for now.
