### ISSUE TITLE
How to update/create cookies from client side?

### ISSUE THREAD

**Issue by ronit-kadwane** [HenrikJoreteg/clientconfig#8]

**Comment by mhamann** [comment]
Not really sure what your question has to do with this lib, but have you looked at https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie?

**Comment by HenrikJoreteg** [comment]
This library is meant just for sending config values to the client. In fact, this line: https://github.com/HenrikJoreteg/clientconfig/blob/91353b004b341faca41aeca07cd55e91abb1782b/clientconfig.js#L10 intentionally expires/wipes out the cookie as soon as its read in.
